// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxwmlykdofndtsrqdmtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4d21seWtkb2ZuZHRzcnFkbXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDAwOTAsImV4cCI6MjA2NDgxNjA5MH0.02MIR1B-aHbLHrJY8Z6YxrSE4xwk7Jcm7zuJ_coxrA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);